package com.example.safeher.bluetooth

enum class BluetoothError {
    BLUETOOTH_DISABLED,
    PERMISSION_DENIED,
    SECURITY_ERROR,
    SCAN_FAILED,
    CONNECTION_FAILED,
    SERVICE_DISCOVERY_FAILED,
    CHARACTERISTIC_NOT_FOUND,
    DISCONNECT_FAILED,
    COMMAND_FAILED,
    DATA_ERROR,
}